apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: nodejs-azure-app
  title: Create a Node.js web application in Azure DevOps
  description: Create a starter Node.js application and deploy it to Azure
  tags:
    - recommended
    - nodejs
    - javascript
    - express
spec:
  owner: janus-authors
  system: janus-idp
  type: service

  parameters:
    - title: Choose a location
      required:
        - orgName
        - projectName
        - repoName
      properties:
        orgName:
          title: Organisation
          type: string
          description: The Organization that this repo will belong to
        projectName:
          title: Project
          type: string
          description: The Project that this repo will belong to
        repoName:
          title: Repository
          type: string
          description: The name of the repository
    - title: Provide information about the new component
      required:
        - owner
        - system
        - port
      properties:
        title:
          title: Title
          type: string
          description: The title of the component
        description:
          title: Description
          type: string
          description: Help others understand what this component is for
        owner:
          title: Owner
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
        system:
          title: System
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System
        port:
          title: Port
          type: number
          default: 3000
          description: Override the port exposed for the application
  steps:
    - id: sourceCodeTemplate
      name: Generating the Source Code Component
      action: fetch:template
      input:
        url: ./skeleton
        values:
          orgName: ${{ parameters.projectName }}
          repoName: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          title: ${{ parameters.title }}
          description: ${{ parameters.description }}
          port: ${{ parameters.port }}
          applicationType: website
          sourceControl: dev.azure.com
    
    - id: publish
      name: Publishing to the Source Code Repository
      action: publish:azure
      input:
        allowedHosts: ['dev.azure.com']
        description: ${{ parameters.description }}
        repoUrl: dev.azure.com?owner=${{ parameters.projectName }}&repo=${{ parameters.repoName }}&organization=${{ parameters.orgName }}
        defaultBranch: main

  output:
    links:
      - title: Open the Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open the Catalog Info Component
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
